Make use of the new bazel-deps on itself

diff --git a/deps b/deps
--- a/deps
+++ b/deps
@@ -2,8 +2,16 @@
 
 ROOT=`pwd`
 
+BAZEL_DEPS_REPO="https://github.com/marcesquerra/bazel-deps.git"
+BAZEL_DEPS_COMMIT="ebe7231d580b91a6491860dbf429084925307a64"
+IDENTIFIER="$BAZEL_DEPS_REPO|$BAZEL_DEPS_COMMIT"
 
-BAZEL_DEPS="/tmp/bazel-deps-runner-$(echo "$PWD" | sha256sum | awk '{ print $1 }')/.bazel-deps/"
+BAZEL_DEPS="/tmp/$(echo "$IDENTIFIER" | sha256sum | awk '{ print $1 }')/.bazel-deps/"
+
+function fail() {
+  echo "$1"
+  exit 1
+}
 
 if [ -e $BAZEL_DEPS ]; then
     if [ ! -d $BAZEL_DEPS ]; then
@@ -14,12 +22,9 @@ if [ -e $BAZEL_DEPS ]; then
     fi
     cd "$BAZEL_DEPS"
 else
-    git clone https://github.com/marcesquerra/bazel-deps.git "$BAZEL_DEPS"
+    git clone "$BAZEL_DEPS_REPO" "$BAZEL_DEPS" || fail "Repo could not be found"
     cd "$BAZEL_DEPS"
+    git checkout "$BAZEL_DEPS_COMMIT" || fail "Commit could not be found"
 fi
 
-COMMIT=9c58185ff901b6945f3ea84aaac1c7ce13304751
-
-(git checkout $COMMIT || (git fetch && git checkout $COMMIT)) &&
-bazel run //:parse -- generate -r $ROOT -s 3rdparty/workspace.bzl -d dependencies.yaml
-
+bazel run //:parse -- generate --repo-root $ROOT --deps "$ROOT/dependencies.yaml" --external 3rdparty 
